-- Creacion de tabla
CREATE TABLE PRODUCTOS (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(200),
    PRECIO NUMBER(10, 2) NOT NULL,
    STOCK NUMBER DEFAULT 0,
    FECHA_CREACION DATE DEFAULT SYSDATE
);

-- Creación de secuencia
CREATE SEQUENCE PRODUCTOS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- TRIGGER (Para el ID automático)
CREATE OR REPLACE TRIGGER TRG_PRODUCTOS_BI
BEFORE INSERT ON PRODUCTOS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT PRODUCTOS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Datos de prueba
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Laptop Dell', 'Core i7 16GB RAM', 1200.50, 10);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Laptop HP Pavilion', 'Ryzen 5 8GB RAM SSD 512GB', 850.00, 15);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('MacBook Air M2', 'Chip M2 256GB Gris Espacial', 1199.99, 5);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Mouse Logitech', 'Inalámbrico Ergonómico', 25.00, 50);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Teclado Mecánico', 'RGB Switch Blue', 80.00, 20);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Monitor Samsung 24"', 'Curvo Full HD 75Hz', 160.00, 12);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Monitor LG UltraGear', 'Gaming 27" 144Hz 1ms', 320.00, 8);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Webcam Logitech C920', 'Full HD 1080p con micrófono estéreo', 75.50, 25);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Disco Duro Externo 1TB', 'Toshiba Canvio Basics USB 3.0', 55.00, 30);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('SSD Kingston 480GB', 'SATA III 2.5" para Laptop/PC', 35.99, 45);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Memoria USB 64GB', 'Kingston DataTraveler Exodia', 8.50, 100);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Impresora Epson L3210', 'Multifuncional EcoTank Tinta Continua', 210.00, 7);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Router TP-Link Archer', 'Dual Band AC1200 WiFi 5', 45.00, 18);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Cable HDMI 2.0', '4K Ultra HD 2 Metros', 12.00, 60);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Silla Gamer', 'Reclinable con soporte lumbar', 189.99, 4);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Tablet Samsung A9', '8.7 Pulgadas 64GB Plateada', 145.00, 10);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Audífonos Sony WH-CH520', 'Inalámbricos Bluetooth 50h batería', 55.00, 22);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Mochila Antirrobo', 'Impermeable con puerto USB', 30.00, 40);

COMMIT;